services:
  context-note:
    build:
      context: ./dev
      dockerfile: Dockerfile
    container_name: context-note
    ports:
      - "8080:3000"
    volumes:
      - ./note:/data/note
    environment:
      - NOTE_ROOT=/data/note
    restart: unless-stopped
